### ISSUE TITLE
CSVs with data

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Eunomia#2]
Would be useful to provide CSVs with the data which could be uploaded into any other DBMS

**Comment by schuemie** [comment]
But the data is already in a nice database... Using database connector you could querySql a table to a data frame, and then insertTable into any other platform. 

Alternatively, we could create a simple function that does the querySql and outputs to CSV, but as mentioned I suspect that is an unnecessary extra step.

(Just trying to keep the package size down).

**Comment by pavgra** [comment]
The reason why I am asking is the presence of such use-case:
- I'd like to add WebAPI tests utilizing the dataset
- To code test I first need to verify the use-case locally, e.g. calculate counts for a certain cohort, and then use the count as a comparator for the test result. Therefore, I'd like to attach the dataset to WebAPI (so would like to have it in Postgres)
- For the Java test itself I'd like to use in-memory H2 database - need to populate it with data also

> Just trying to keep the package size down

Wouldn't `.Rbuildignore` allow to not include the CSVs into the R package but keep them in VCS?

**Comment by schuemie** [comment]
I added a function to export to CSV. That is the best I can do.

**Comment by pavgra** [comment]
Thank you, @schuemie !
