### ISSUE TITLE
issue with dates in cohort

### ISSUE THREAD

**Issue by jreps** [OHDSI/Eunomia#20]
Hi,

I was testing some PatientLevelPrediction code and I noticed an error when I tried to select from a cohort table where the cohort_start_date is between two user input dates.

The code: "select * from main.cohort where cohort_start_date <= cast('20050101' as date) and cohort_start_date >= cast('19500101' as date) ;" returns an empty data.frame but there are dates between 1950 and 2005.

I checked the SqlRender and the cast('', as date) is kept when converting to sqlite, but I suspect this should be something else, so maybe that is the issue?

**Comment by schuemie** [comment]
I've fixed this in [this commit](https://github.com/OHDSI/SqlRender/commit/ec4c16f425b886032f74d2f4a1e6cb7a08a40b70) in SqlRender. I'll create a new release soon.
