### ISSUE TITLE
GI Cohort (cohortid = 3) has null cohort_end_date

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Eunomia#22]
This sql shows that cohortEndDate has NA (null) as cohort_end_date:

```
sql <- "
SELECT TOP 5 *
FROM main.cohort
WHERE cohort_definition_id = 3;
"
renderTranslateQuerySql(connection, sql, snakeCaseToCamelCase = TRUE)
# cohortDefinitionId subjectId cohortStartDate cohortEndDate
# 1                  3       273      2011-10-10          <NA>
#   2                  3        61      2005-09-15          <NA>
#   3                  3       351      2018-06-28          <NA>
#   4                  3       579      1999-11-06          <NA>
#   5                  3       549      1987-12-28          <NA>
```

Here’s the cohort SQL: https://github.com/OHDSI/Eunomia/blob/main/inst/sql/sql_server/GiBleed.sql

The bug is that cohorts should all have start and end dates, so this sql should be modified to default to some kind of end date, either condition_date +1d or make it end at the end of the containing observation period.

**Comment by priagopal** [comment]
Hi Chris and Adam,

I am not able to assign the issue to myself to fix it. Can you please assign it to me.

Thanks,
priya

**Comment by ablack3** [comment]
I think this was actually fixed in the develop branch.
