### ISSUE TITLE
CRAN and support for multiple CDMs

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Eunomia#23]
I think one of the challenges with keeping Eunomia on CRAN is the size of the package.  The mini CDM embedded in Eunomia is 5.1 MB. Additionally it would be very helpful to allow for the possibility of multiple Eunomia datasets. For example the current CDM is not very helpful for testing code that requires cancer related concepts. In have created cancer specific mini-CDM to test code that requires cancer cohorts to be non-empty.

What if we thought of Eunomia as a "[data access package](https://www.r-bloggers.com/2016/08/r-packages-for-data-access/)" and rather than embed the CDM inside the package we provide functionality to easily download and connect to numerous mini-CDMs. 

The size of the package submitted to CRAN would be much smaller and we could support multiple mini-CDMs for various domains and use cases (like oncology).

The CDMs would be stored on github in this repo but not submitted to CRAN. This setup would be analogous to https://github.com/mlverse/torchdatasets. Eunomia::getEunomiaConnectionDetails("oncology") would ask the user if they want to download the oncology eunomia dataset from github. 
 
The goal would be to 1) keep Eunomia on CRAN and 2) allow for more than one mini-cdm for testing.

**Comment by schuemie** [comment]
This would then follow the same pattern as DatabaseConnector, where for the same reason we moved the JDBC drivers to [a Github repo](https://github.com/OHDSI/DatabaseConnectorJars/tree/main/docs), and added a [function to download those on the fly](https://github.com/OHDSI/DatabaseConnector/blob/main/R/Drivers.R#L55).

**Comment by fdefalco** [comment]
If we wanted to leverage Synthea, we could create template modules in ETL-Synthea for various builds, or perhaps use another repository for the modules if we preferred. It might help to have traceability back to modules so that if we want to improve a particular mini-cdm we would know which modules generated the patient populations.  

Unfortunately Synthea doesn't have many existing modules that would help us build a mental health data set, however I would be happy to help with module development to generate them and contribute them back to Synthea.  Here is their current open source module library.  https://github.com/synthetichealth/synthea/wiki/Module-Gallery

**Comment by ablack3** [comment]
> traceability back to modules so that if we want to improve a particular mini-cdm we would know which modules generated the patient populations.

I like the idea of having traceability.

This might be a stretch but is there any reason why we couldn't also have a Eunomia-mimic CDM that contained the [publicly available MIMIC sample](https://physionet.org/content/mimiciii-demo/1.4/#:~:text=MIMIC%2DIII%20is%20a%20large,2001%20and%202012%20%5B1%5D.) mapped to OMOP?

https://physionet.org/content/mimic-iv-demo-omop/0.9/
https://github.com/MIT-LCP/mimic-omop

**Comment by anthonysena** [comment]
[HADES Hack-a-thon]: Sena is going to work on this item.

**Comment by anthonysena** [comment]
Adding some notes/to-do items from the HADES Hack-a-thon:

- [ ] Create a new repository to store the Eunomia data sets
- [ ] Define a structure for storing the Eunomia data sets to support different version of OMOP CDM
- [ ] Define the storage for the data sets (proposed to have a .ZIP of the CDM tables as .CSV files)
- [ ] Export the Eunomia data to .CSV for storage in the Eunomia data set repo
- [ ] Create a set of Eunomia functions for downloading the Eunomia data sets. This will use an environment variable to declare where the Eunomia data sets as mentioned in the comment above.
- [ ] Remove the embedded SQLite file once the items above are complete

**Comment by anthonysena** [comment]
### Define the storage for the data sets

Proposed storage structure:

`/EunomiaDataSets/datasets/<dataset name>/<dataset name>_<cdm version>.zip`

So for the current data set in Eunomia, the storage will be:

`/EunomiaDataSets/datasets/GiBleed/GiBleed_5.3.zip`

**Comment by ablack3** [comment]
It seems cran complains about a package caching data on a user's computer but maybe this package does it in compliance with the CRAN policy. https://cran.r-project.org/web/packages/pkgfilecache/vignettes/pkgfilecache.html

**Comment by ablack3** [comment]
FYI I went ahead and put this code on CRAN in the CDMConnector package because we need it for testing in Darwin. Once Eunomia is back on CRAN I'll remove it and depend on Eunomia. I hope that is ok with everyone.

If you anyone wants to test it here is a reprex using duckdb and DBI.

``` r
# install.packages("CDMConnector")
library(CDMConnector)

downloadEunomiaData("GiBleed", overwrite = TRUE)

con <- DBI::dbConnect(duckdb::duckdb(), eunomia_dir())

DBI::dbListTables(con)
#>  [1] "care_site"             "cdm_source"            "cohort"               
#>  [4] "cohort_attribute"      "concept"               "concept_ancestor"     
#>  [7] "concept_class"         "concept_relationship"  "concept_synonym"      
#> [10] "condition_era"         "condition_occurrence"  "cost"                 
#> [13] "death"                 "device_exposure"       "domain"               
#> [16] "dose_era"              "drug_era"              "drug_exposure"        
#> [19] "drug_strength"         "fact_relationship"     "location"             
#> [22] "measurement"           "metadata"              "note"                 
#> [25] "note_nlp"              "observation"           "observation_period"   
#> [28] "payer_plan_period"     "person"                "procedure_occurrence" 
#> [31] "provider"              "relationship"          "source_to_concept_map"
#> [34] "specimen"              "visit_detail"          "visit_occurrence"     
#> [37] "vocabulary"

DBI::dbDisconnect(con, shutdown = FALSE)
```

<sup>Created on 2023-01-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
