### ISSUE TITLE
Does the order of columns matter in the CDM specification?

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Eunomia#55]
Should the column order of a CDM match the order in the specification or can the columns be in any order and still be considered a valid CDM?

In Eunomia GiBleed I see that the column order in the condition_occurrence table does not match the column order in the 5.3 specification.  Is this an error or can columns be in any order in a CDM?

<img width="803" alt="image" src="https://github.com/OHDSI/Eunomia/assets/10227522/687792d3-714e-4713-9c26-dfbfae8b8313">
https://ohdsi.github.io/CommonDataModel/cdm53.html#CONDITION_OCCURRENCE

``` r
library(DatabaseConnector)
con <- connect(Eunomia::getEunomiaConnectionDetails())
#> Connecting using SQLite driver
querySql(con, "select * from main.condition_occurrence limit 0")
#>  [1] CONDITION_OCCURRENCE_ID       PERSON_ID                    
#>  [3] CONDITION_CONCEPT_ID          CONDITION_START_DATE         
#>  [5] CONDITION_START_DATETIME      CONDITION_END_DATE           
#>  [7] CONDITION_END_DATETIME        CONDITION_TYPE_CONCEPT_ID    
#>  [9] STOP_REASON                   PROVIDER_ID                  
#> [11] VISIT_OCCURRENCE_ID           VISIT_DETAIL_ID              
#> [13] CONDITION_SOURCE_VALUE        CONDITION_SOURCE_CONCEPT_ID  
#> [15] CONDITION_STATUS_SOURCE_VALUE CONDITION_STATUS_CONCEPT_ID  
#> <0 rows> (or 0-length row.names)
disconnect(con)
packageVersion("Eunomia")
#> [1] '1.0.2'
```

<sup>Created on 2023-07-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

CONDITION_STATUS_CONCEPT_ID comes at the end but in the specification it comes before STOP_REASON.

**Comment by clairblacketer** [comment]
Hi @ablack3 so since we only look for the presence of columns in the DQD and we allow data partners to add their own site-specific columns, I personally do not think we should mandate a particular order to deem a CDM valid.

**Comment by ablack3** [comment]
Good to know. Thanks @clairblacketer!
