### ISSUE TITLE
Provide an option for caching the database?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Eunomia#63]
I use Eunomia a lot while developing, and with the new version (that downloads the data from the world wide web) it has to download the same database every time (which can be dozens of times in a single development session). Might we support some caching mechanism? 

For example, if we detect the user specified a EUNOMIA_CACHE_FOLDER environmental variable, the first time we can download the database to that folder, then create a copy in temp and hand that to the user. The next time, we can check if the database already exists in the cache folder, and don't have to download. We could use the file name in the cache folder to distinguish between different versions or types of data. The function signature could become:

```r
getEunomiaConnectionDetails <- function(databaseFile = tempfile(fileext = ".sqlite"), 
                                        dbms = "sqlite",
                                        cacheFolder = Sys.getenv("EUNOMIA_CACHE_FOLDER")) {

```

**Comment by fdefalco** [comment]
https://github.com/OHDSI/Eunomia/issues/62 should address this, just updated yesterday into the develop branch. Does that suffice?

**Comment by schuemie** [comment]
Yes, that seems to work. I must admit I expected the EUNOMIA_DATA_FOLDER environmental variable to work differently, given me a single instance where changes would perpetuate between sessions. But instead it works exactly as I described above, so it certainly solves my problem!
