### ISSUE TITLE
Error message when installing in R Studio

### ISSUE THREAD

**Issue by rward3182** [OHDSI/Eunomia#7]
Hi I get this message from R Studio when trying to install. 

Error: Failed to install 'Eunomia' from GitHub:
  (converted from warning) unable to access index for repository https://OHDSI.github.io/drat/bin/windows/contrib/3.6:
  cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.6/PACKAGES'

It gives a 404 when I put into a browser. It looks like the file is not there.

**Comment by schuemie** [comment]
For some reason drat always first tries to install the binary version of the package, which doesn't exist. But then it should automatically search for the source package, which [does exist](https://github.com/OHDSI/drat/blob/gh-pages/src/contrib/Eunomia_1.0.0.tar.gz). Is there no request to install from source after this initial error message?

**Comment by Aqsa-Mahmood** [comment]
> Hi I get this message from R Studio when trying to install.
> 
> Error: Failed to install 'Eunomia' from GitHub: (converted from warning) unable to access index for repository https://OHDSI.github.io/drat/bin/windows/contrib/3.6: cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.6/PACKAGES'
> 
> It gives a 404 when I put into a browser. It looks like the file is not there.


i encounter the same problem... can u plz share the solution ,in case u got any??

**Comment by Aqsa-Mahmood** [comment]
Hi! i get this error from R Studio when trying to  install.

 ERROR: dependency 'Eunomia' is not available for package 'Hades'
* removing 'C:/R/R-4.1.1/library/Hades'
Warning messages:
1: package ‘Eunomia’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,

**Comment by chrisknoll** [comment]
When following the instructions to execute the following:
```
install.packages("Eunomia")
```

The error 'package ‘Eunomia’ is not available for this version of R'.  I'm running R 4.1.

The reason why we can't work around this with `devtools::install_github()` is that git actions that `Suggests` Eunomia are failing.  Unless there is another way to install dependent packages in git actions via install_github()?

**Comment by chrisknoll** [comment]
I managed to get the build to work in git actions by
- Adding GITHUB_PAT: ${{ secrets.GH_TOKEN }} to the env: section of the R_CMD_check_Hades.yaml
- Adding Remotes: section in DESCRIPTION referencing OHDSI/Eunomia

**Comment by sshahraz** [comment]
I tried devtools. It does not work. I appreciate if someone suggests an alternative way.

**Comment by ablack3** [comment]
As an alternative how about

`git clone https://github.com/OHDSI/Eunomia`
`Rscript -e 'devtools::install("Eunomia")'`

from the terminal/command prompt?

On windows you might have to use `Rscript.exe -e 'devtools::install("Eunomia")'` and make sure R is on your path.

**Comment by smusali** [comment]
Hi, everyone!

I guess this must be documented inside `README.md` for newcomers.
