### ISSUE TITLE
Description and origin of datasets

### ISSUE THREAD

**Issue by eroell** [OHDSI/Eunomia#70]
I have been looking for a description/origin of the datasets.

For the MIMIC-IV Demo, I'm aware of its origin on [physionet](https://physionet.org/content/mimic-iv-demo-omop/0.9/).
For Synthea27Nj and GiBleed I'm not, and couldnt find a link, or description, or similar to above

**Comment by fdefalco** [comment]
Synthea27Nj and GiBleed were generated using [Synthea](https://github.com/synthetichealth/synthea)
