### ISSUE TITLE
Add description of how this data is simulated

### ISSUE THREAD

**Issue by SulevR** [OHDSI/Eunomia#8]
Please add some comments about how this data is simulated - how many patients, how the conditions/procedures/observations are selected/generated etc. This information is important when considering for which tests one can use this package.

**Comment by fdefalco** [comment]
This data was simulated using Synthea (https://github.com/synthetichealth/synthea).  The data is only intended to be used for tests of the CohortMethod package as specified in the Book of OHDSI.
